In [1]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_csv('AUCs.txt',sep='\t')

In [11]:
data = data.rename(columns={'Unnamed: 0':'samples'})

In [19]:
from scipy import stats

In [23]:
p_values = []
for i in range(1,5):
    for j in range(1,5):
        if i<j:
            p_values.append(stats.wilcoxon(data.iloc[:,i],data.iloc[:,j]).pvalue)
            print "P-value between {} and {} is {}".format(data.columns[i], data.columns[j] ,\
                                                           stats.wilcoxon(data.iloc[:,i],data.iloc[:,j]).pvalue)

P-value between C4.5 and C4.5+m is 0.0107571331198
P-value between C4.5 and C4.5+cf is 0.861262330095
P-value between C4.5 and C4.5+m+cf is 0.0159064441017
P-value between C4.5+m and C4.5+cf is 0.0463327297934
P-value between C4.5+m and C4.5+m+cf is 0.327825675845
P-value between C4.5+cf and C4.5+m+cf is 0.0229090993544


In [24]:
p_values

[0.01075713311978963,
 0.86126233009534803,
 0.015906444101703374,
 0.046332729793395394,
 0.32782567584464062,
 0.022909099354356588]

In [25]:
from statsmodels.sandbox.stats.multicomp import multipletests

In [26]:
multipletests(p_values,alpha=0.05,method='holm')

(array([False, False, False, False, False, False], dtype=bool),
 array([ 0.0645428 ,  0.86126233,  0.07953222,  0.13899819,  0.65565135,
         0.0916364 ]),
 0.008512444610847103,
 0.008333333333333333)

In [27]:
multipletests(p_values,alpha=0.05,method='fdr_bh')

(array([ True, False,  True, False, False,  True], dtype=bool),
 array([ 0.0458182 ,  0.86126233,  0.0458182 ,  0.06949909,  0.39339081,
         0.0458182 ]),
 0.008512444610847103,
 0.008333333333333333)